name: flutter2048
description: "2048 game developed on Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any
  intl: any
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0

  equatable: ^2.0.5
  clock: ^1.1.1

  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5

  stack_trace: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.7
  mocktail: ^1.0.4

  flutter_lints: ^5.0.0

  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true
