version: "3"

tasks:
  flutter:get:
    desc: Get flutter dependencies
    summary: |
      Get flutter dependencies
    cmds:
      - flutter pub get

  dart:gen:
    desc: Generate dart files
    summary: |
      Run codegen
    cmds:
      - dart run build_runner build -d

  dart:gen:watch:
    desc: Generate dart files
    summary: |
      Watch codegen
    cmds:
      - dart run build_runner watch -d
